const TRIPLE_BACKTICK = '```';
const DOUBLE_BACKTICK = '``';
const SINGLE_BACKTICK = '`';

module.exports = {
    TRIPLE_BACKTICK: TRIPLE_BACKTICK,
    DOUBLE_BACKTICK: DOUBLE_BACKTICK,
    SINGLE_BACKTICK: SINGLE_BACKTICK
}